// Try and Catch

// try {
     // block of code for testing.
//     let x = undefined
//     console.log(x[0])
// } catch (err){
     // block of code for testing.
//     console.log("error handling in catch",err)
// } finally {
    // block of code to run after try-catch
//     console.log("Finally always gets executed")
// }

// - Use of try catch in real world Application class 22

try {
    console.log("hello Wordl")
    // console.log(a)
    console.log("ending try")
} catch (err){
    console.log("handled",err)
} finally {
    console.log("finaly")
}

console.log("end")